// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oglduptdtrlxqglapjaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbGR1cHRkdHJseHFnbGFwamFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODc0MTQsImV4cCI6MjA2OTQ2MzQxNH0.d2ru2MwWfA_AzCyRylRVS3uEpUXuH1X9r6ya3nCbAm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});